### ISSUE TITLE
Video has disabled comments

### ISSUE THREAD

**Issue by plsgeniusman** [hobogalaxy/youtube_multi_video_comment_downloader#1]
All videos appear with this message.

**Comment by hobogalaxy** [comment]
Seems like youtube changed something and now you need to manually enable their API. Go to https://console.developers.google.com/apis/library/youtube.googleapis.com and click 'enable' if the button appears.
If it still doesn't work then go to console.developers.google.com/apis/api/youtube.googleapis.com/credentials and in the top left corner you should be able to see name of the project and option to create new project. Create new project, switch to it, enable API for that project and generate new key (that's what works for me).

**Comment by weekagooooo323** [comment]
Seems to have fixed the issue. Do you have a Discord I can add? Need a custom implementation, and can pay.
